version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    volumes:
      - openwebui:/app/backend/data
    environment:
      - OPENAI_API_BASE_URL=http://localhost:11434/v1
      - OPENAI_API_KEY=ollama
      - WEBUI_SECRET_KEY=your-secret-key-here
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
  openwebui:
  ollama:
